name = "TensorKitTensors"
uuid = "41b62e7d-e9d1-4e23-942c-79a97adf954b"
authors = ["QuantumKitHub"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"

[compat]
Aqua = "0.8.9"
LinearAlgebra = "1"
TensorKit = "0.13.2"
Test = "1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
