module QuantumGates

using TensorKit
using LinearAlgebra: I
using RationalRoots: signedroot
import ..TensorKitTensors: symmetrize, desymmetrize, @operator
import ..TensorKitTensors: _custom_dense_operator, _check_custom_space

export qubit_space, basis_transform, custom, controlled
export pauli_x, pauli_y, pauli_z, proj_0, proj_1, hadamard, s_gate, t_gate
export phase_shift, rotation_x, rotation_y, rotation_z, u3
export cnot, cy, cz, cphase, ch, cs, swap, iswap, dcx, ecr
export rotation_xx, rotation_yy, rotation_zz, rotation_zx
export toffoli, fredkin
export X, Y, Z, P0, P1, H, S, T, P, Rx, Ry, Rz, U
export CNOT, CX, CY, CZ, CP, CH, CS, SWAP, ISWAP, DCX, ECR
export Rxx, Ryy, Rzz, Rzx
export TOFFOLI, CCX, FREDKIN, CSWAP

"""
    qubit_space([symmetry::Type{<:Sector}])

Return the local Hilbert space of a single qubit with basis ``|0⟩, |1⟩``.

| Symmetry | Space |
|---|---|
| `Trivial` | `ComplexSpace(2)` |
| `Z2Irrep` | `Z2Space(0 => 1, 1 => 1)` (charge = number of excitations mod 2) |
| `U1Irrep` | `U1Space(0 => 1, 1 => 1)` (charge = number of excitations) |
"""
qubit_space(::Type{Trivial} = Trivial) = ComplexSpace(2)
qubit_space(::Type{Z2Irrep}) = Z2Space(0 => 1, 1 => 1)
qubit_space(::Type{U1Irrep}) = U1Space(0 => 1, 1 => 1)
qubit_space(symmetry::Type{<:Sector}) = throw(ArgumentError("invalid symmetry `$symmetry`"))

"""
    basis_transform(symmetry::Type{<:Sector})

Return the unitary basis transformation that maps the computational basis
``\\{|0⟩, |1⟩\\}`` of `qubit_space(Trivial)` onto the basis of `qubit_space(symmetry)`, as a
`TensorMap` from `qubit_space(Trivial)` to `desymmetrize(qubit_space(symmetry))`, as required
by [`symmetrize`](@ref TensorKitTensors.symmetrize).

| Symmetry | Transformation |
|---|---|
| `Trivial` | identity |
| `Z2Irrep` | identity |
| `U1Irrep` | identity |

Both `Z2Irrep` and `U1Irrep` use the (parity of the) excitation number as their charge, which
is diagonal in the computational basis, and order their sectors as ``0, 1``, such that the
transformation is the identity in all cases. It is returned with integer scalar type, such
that it promotes to any scalar type without loss of precision.
"""
function basis_transform(symmetry::Type{<:Sector})
    V = desymmetrize(qubit_space(symmetry))
    return TensorMap(Matrix{Int}(I, 2, 2), V ← qubit_space(Trivial))
end

# Symmetrize a gate through its basis transformation. The keywords of the parametrized gates
# are accepted and discarded: `qubit_space` and `basis_transform` do not depend on them.
_symmetrize_operator(O::AbstractTensorMap, symmetry::Type{<:Sector}; kwargs...) =
    symmetrize(O, basis_transform(symmetry), qubit_space(symmetry))

"""
    custom(A::AbstractArray, symmetry::Type{<:Sector}; tol=nothing)

Construct a symmetry-aware qubit operator from a dense rank-`2N` array in the computational basis.
The axes must be ordered as `(out₁, …, outₙ, in₁, …, inₙ)` and every axis must have dimension two.
"""
function custom(A::AbstractArray, symmetry::Type{<:Sector}; tol = nothing)
    O = _check_custom_space(_custom_dense_operator(A), qubit_space(Trivial))
    return symmetrize(O, basis_transform(symmetry), qubit_space(symmetry); tol)
end

# Gate combinators
# ----------------
"""
    controlled(G::AbstractTensorMap)

Return the controlled version ``|0⟩⟨0| ⊗ I + |1⟩⟨1| ⊗ G`` of the gate `G`, which applies `G`
to the qubits of `G` if an additional leading control qubit is in the state ``|1⟩``.

The element type and the symmetry are inherited from `G`. Since a controlled gate conserves
whatever `G` conserves, this is compatible with every symmetry that `G` itself supports.
Controls can be stacked, e.g. `controlled(controlled(pauli_x()))` is the [`toffoli`](@ref)
gate, and using [`proj_1`](@ref) as the leading projector instead gives a gate controlled on
``|0⟩``.

# Examples

The controlled x-rotation, which is not provided as a gate of its own:

```jldoctest
julia> using TensorKit, TensorKitTensors.QuantumGates;

julia> crx = controlled(rotation_x(; theta = π / 2));

julia> crx ≈ proj_0() ⊗ id(qubit_space()) + proj_1() ⊗ rotation_x(; theta = π / 2)
true
```
"""
function controlled(G::AbstractTensorMap)
    elt, symmetry = scalartype(G), sectortype(G)
    # `one(G)` inherits the scalar type of `G`, unlike `id(space)`, which defaults to `Float64`
    return proj_0(elt, symmetry) ⊗ one(G) + proj_1(elt, symmetry) ⊗ G
end

# Helpers
# -------
# Explicit error for the gates that are not representable with a real scalar type, in place of
# the `MethodError` that a `::Type{<:Complex}` annotation would give.
_require_complex(elt::Type{<:Number}, gate::Symbol) =
    elt <: Real && throw(ArgumentError("`$gate` requires `elt <: Complex`"))

# The rotation ``e^{-iθO/2} = \cosθ/2 - i\sinθ/2 O`` generated by an involution, ``O² = 1``.
# The trigonometric factors are converted to the scalar type of `O`, such that the requested
# element type is neither widened nor narrowed by that of the angle.
function _rotation(O::AbstractTensorMap, theta)
    s, c = sincos(theta / 2)
    T = scalartype(O)
    return convert(T, c) * one(O) - convert(T, im * s) * O
end

# Pauli gates
# -----------
"""
    pauli_x([eltype::Type{<:Number}], [symmetry::Type{<:Sector}])
    X([eltype::Type{<:Number}], [symmetry::Type{<:Sector}])

The Pauli-X (NOT) gate ``\\begin{pmatrix} 0 & 1 \\\\ 1 & 0 \\end{pmatrix}``.

Supported symmetries: `Trivial`.
"""
@operator X function pauli_x(elt::Type{<:Number}, ::Type{Trivial})
    return TensorMap(elt[0 1; 1 0], qubit_space() ← qubit_space())
end

"""
    pauli_y([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}])
    Y([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}])

The Pauli-Y gate ``\\begin{pmatrix} 0 & -i \\\\ i & 0 \\end{pmatrix}``.

Supported symmetries: `Trivial`.
"""
@operator Y function pauli_y(elt::Type{<:Number}, ::Type{Trivial})
    _require_complex(elt, :pauli_y)
    return TensorMap(elt[0 -im; im 0], qubit_space() ← qubit_space())
end

"""
    pauli_z([eltype::Type{<:Number}], [symmetry::Type{<:Sector}])
    Z([eltype::Type{<:Number}], [symmetry::Type{<:Sector}])

The Pauli-Z gate ``\\begin{pmatrix} 1 & 0 \\\\ 0 & -1 \\end{pmatrix}``.

Supported symmetries: `Trivial`, `Z2Irrep`, `U1Irrep`.
"""
@operator Z function pauli_z(elt::Type{<:Number}, ::Type{Trivial})
    return TensorMap(elt[1 0; 0 -1], qubit_space() ← qubit_space())
end

# Projectors
# ----------
"""
    proj_0([eltype::Type{<:Number}], [symmetry::Type{<:Sector}])
    P0([eltype::Type{<:Number}], [symmetry::Type{<:Sector}])

The projector onto ``|0⟩``, ``|0⟩⟨0| = \\tfrac{1}{2}(I + Z)``.

Supported symmetries: `Trivial`, `Z2Irrep`, `U1Irrep`.
"""
@operator P0 function proj_0(elt::Type{<:Number}, ::Type{Trivial})
    return TensorMap(elt[1 0; 0 0], qubit_space() ← qubit_space())
end

"""
    proj_1([eltype::Type{<:Number}], [symmetry::Type{<:Sector}])
    P1([eltype::Type{<:Number}], [symmetry::Type{<:Sector}])

The projector onto ``|1⟩``, ``|1⟩⟨1| = \\tfrac{1}{2}(I - Z)``.

Supported symmetries: `Trivial`, `Z2Irrep`, `U1Irrep`.
"""
@operator P1 function proj_1(elt::Type{<:Number}, ::Type{Trivial})
    return TensorMap(elt[0 0; 0 1], qubit_space() ← qubit_space())
end

# Derived single-qubit gates
# --------------------------
"""
    hadamard([eltype::Type{<:Number}], [symmetry::Type{<:Sector}])
    H([eltype::Type{<:Number}], [symmetry::Type{<:Sector}])

The Hadamard gate ``H = \\tfrac{1}{√2}(X + Z)``.

Supported symmetries: `Trivial`.
"""
@operator H function hadamard(elt::Type{<:Number}, ::Type{Trivial})
    h = signedroot(1 // 2)
    return TensorMap(elt[h h; h (-h)], qubit_space() ← qubit_space())
end

"""
    phase_shift([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}]; theta)
    P([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}]; theta)

The phase-shift gate ``\\mathrm{diag}(1, e^{iθ}) = |0⟩⟨0| + e^{iθ} |1⟩⟨1|``, with required
rotation angle `theta`.

Supported symmetries: `Trivial`, `Z2Irrep`, `U1Irrep`.
"""
@operator P function phase_shift(elt::Type{<:Number}, ::Type{Trivial}; theta)
    _require_complex(elt, :phase_shift)
    return TensorMap(elt[1 0; 0 cis(theta)], qubit_space() ← qubit_space())
end

"""
    s_gate([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}])
    S([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}])

The phase gate ``S = √Z = \\mathrm{diag}(1, i)``, i.e. `phase_shift(; theta=π/2)`.
Its adjoint ``S^†`` is `s_gate()'`.

Supported symmetries: `Trivial`, `Z2Irrep`, `U1Irrep`.
"""
@operator S function s_gate(elt::Type{<:Number}, ::Type{Trivial})
    _require_complex(elt, :s_gate)
    return proj_0(elt, Trivial) + im * proj_1(elt, Trivial)
end

"""
    t_gate([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}])
    T([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}])

The ``T`` (π/8) gate ``T = √S = \\mathrm{diag}(1, e^{iπ/4})``, i.e. `phase_shift(; theta=π/4)`.
Its adjoint ``T^†`` is `t_gate()'`.

Supported symmetries: `Trivial`, `Z2Irrep`, `U1Irrep`.
"""
@operator T function t_gate(elt::Type{<:Number}, ::Type{Trivial})
    _require_complex(elt, :t_gate)
    # `signedroot` keeps ``e^{iπ/4} = (1 + i)/√2`` exact for any scalar type
    h = convert(elt, signedroot(1 // 2))
    return proj_0(elt, Trivial) + h * (1 + im) * proj_1(elt, Trivial)
end

"""
    rotation_x([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}]; theta)
    Rx([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}]; theta)

The x-rotation gate ``e^{-iθX/2} = \\cos\\tfrac{θ}{2}\\,I - i\\sin\\tfrac{θ}{2}\\,X``, with
required rotation angle `theta`.

Supported symmetries: `Trivial`.
"""
@operator Rx function rotation_x(elt::Type{<:Number}, ::Type{Trivial}; theta)
    _require_complex(elt, :rotation_x)
    return _rotation(pauli_x(elt, Trivial), theta)
end

"""
    rotation_y([eltype::Type{<:Number}], [symmetry::Type{<:Sector}]; theta)
    Ry([eltype::Type{<:Number}], [symmetry::Type{<:Sector}]; theta)

The y-rotation gate ``e^{-iθY/2} = \\cos\\tfrac{θ}{2}\\,I - i\\sin\\tfrac{θ}{2}\\,Y``, with
required rotation angle `theta`. Unlike the other rotations, this one is real-valued.

Supported symmetries: `Trivial`.
"""
@operator Ry function rotation_y(elt::Type{<:Number}, ::Type{Trivial}; theta)
    R = _rotation(pauli_y(complex(elt), Trivial), theta)
    return elt <: Real ? real(R) : R
end

"""
    rotation_z([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}]; theta)
    Rz([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}]; theta)

The z-rotation gate ``e^{-iθZ/2} = \\cos\\tfrac{θ}{2}\\,I - i\\sin\\tfrac{θ}{2}\\,Z``, with
required rotation angle `theta`.

Supported symmetries: `Trivial`, `Z2Irrep`, `U1Irrep`.
"""
@operator Rz function rotation_z(elt::Type{<:Number}, ::Type{Trivial}; theta)
    _require_complex(elt, :rotation_z)
    return _rotation(pauli_z(elt, Trivial), theta)
end

"""
    u3([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}]; theta, phi, lambda)
    U([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}]; theta, phi, lambda)

The universal single-qubit gate
```math
U(θ, φ, λ) = \\begin{pmatrix}
    \\cos\\tfrac{θ}{2} & -e^{iλ}\\sin\\tfrac{θ}{2} \\\\
    e^{iφ}\\sin\\tfrac{θ}{2} & e^{i(φ+λ)}\\cos\\tfrac{θ}{2}
\\end{pmatrix}
= e^{i(φ+λ)/2}\\, R_z(φ)\\, R_y(θ)\\, R_z(λ),
```
with required angles `theta`, `phi` and `lambda`. Every single-qubit gate is a special case of
it, e.g. `u3(; theta = 0, phi = 0, lambda = θ)` is [`phase_shift`](@ref) and
`u3(; theta = π, phi = 0, lambda = π)` is [`pauli_x`](@ref).

Supported symmetries: `Trivial`.
"""
@operator U function u3(elt::Type{<:Number}, ::Type{Trivial}; theta, phi, lambda)
    _require_complex(elt, :u3)
    s, c = sincos(theta / 2)
    return TensorMap(
        elt[c (-cis(lambda) * s); (cis(phi) * s) (cis(phi + lambda) * c)],
        qubit_space() ← qubit_space()
    )
end

# Two-qubit gates
# ---------------
"""
    cnot([eltype::Type{<:Number}], [symmetry::Type{<:Sector}])
    CNOT([eltype::Type{<:Number}], [symmetry::Type{<:Sector}])
    CX([eltype::Type{<:Number}], [symmetry::Type{<:Sector}])

The controlled-NOT gate ``|0⟩⟨0| ⊗ I + |1⟩⟨1| ⊗ X``: applies [`pauli_x`](@ref) to the second qubit if the first is ``|1⟩``.

Supported symmetries: `Trivial`.
"""
@operator CNOT function cnot(elt::Type{<:Number}, ::Type{Trivial})
    return controlled(pauli_x(elt, Trivial))
end
const CX = cnot

"""
    cy([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}])
    CY([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}])

The controlled-Y gate ``|0⟩⟨0| ⊗ I + |1⟩⟨1| ⊗ Y``: applies [`pauli_y`](@ref) to the second qubit if the first is ``|1⟩``.

Supported symmetries: `Trivial`.
"""
@operator CY function cy(elt::Type{<:Number}, ::Type{Trivial})
    _require_complex(elt, :cy)
    return controlled(pauli_y(elt, Trivial))
end

"""
    ch([eltype::Type{<:Number}], [symmetry::Type{<:Sector}])
    CH([eltype::Type{<:Number}], [symmetry::Type{<:Sector}])

The controlled-Hadamard gate ``|0⟩⟨0| ⊗ I + |1⟩⟨1| ⊗ H``: applies [`hadamard`](@ref) to the second qubit if the first is ``|1⟩``.

Supported symmetries: `Trivial`.
"""
@operator CH function ch(elt::Type{<:Number}, ::Type{Trivial})
    return controlled(hadamard(elt, Trivial))
end

"""
    cphase([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}]; theta)
    CP([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}]; theta)

The controlled phase-shift gate ``\\mathrm{diag}(1, 1, 1, e^{iθ})``, with required rotation
angle `theta`: applies [`phase_shift`](@ref) to the second qubit if the first is ``|1⟩``.

Supported symmetries: `Trivial`, `Z2Irrep`, `U1Irrep`.
"""
@operator CP function cphase(elt::Type{<:Number}, ::Type{Trivial}; theta)
    _require_complex(elt, :cphase)
    return controlled(phase_shift(elt, Trivial; theta))
end

"""
    cz([eltype::Type{<:Number}], [symmetry::Type{<:Sector}])
    CZ([eltype::Type{<:Number}], [symmetry::Type{<:Sector}])

The controlled-Z gate ``\\mathrm{diag}(1, 1, 1, -1)``, i.e. `cphase(; theta=π)`.

Supported symmetries: `Trivial`, `Z2Irrep`, `U1Irrep`.
"""
@operator CZ function cz(elt::Type{<:Number}, ::Type{Trivial})
    return controlled(pauli_z(elt, Trivial))
end

"""
    cs([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}])
    CS([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}])

The controlled-``S`` gate ``\\mathrm{diag}(1, 1, 1, i)``, i.e. `cphase(; theta=π/2)`.

Supported symmetries: `Trivial`, `Z2Irrep`, `U1Irrep`.
"""
@operator CS function cs(elt::Type{<:Number}, ::Type{Trivial})
    _require_complex(elt, :cs)
    return controlled(s_gate(elt, Trivial))
end

"""
    swap([eltype::Type{<:Number}], [symmetry::Type{<:Sector}])
    SWAP([eltype::Type{<:Number}], [symmetry::Type{<:Sector}])

The gate that swaps two qubits, ``|ab⟩ ↦ |ba⟩``.

Supported symmetries: `Trivial`, `Z2Irrep`, `U1Irrep`.
"""
@operator SWAP function swap(elt::Type{<:Number}, ::Type{Trivial})
    q = qubit_space()
    return permute(id(elt, q ⊗ q), ((1, 2), (4, 3)))
end

"""
    iswap([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}])
    ISWAP([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}])

The iSWAP gate, swapping two qubits with an extra factor ``i`` on the ``|01⟩ ↔ |10⟩`` amplitudes.

Supported symmetries: `Trivial`, `Z2Irrep`, `U1Irrep`.
"""
@operator ISWAP function iswap(elt::Type{<:Number}, ::Type{Trivial})
    _require_complex(elt, :iswap)
    # `D` is the part of the swap that is diagonal in the computational basis, such that
    # `swap - D` is the ``|01⟩ ↔ |10⟩`` exchange that picks up the factor ``i``
    D = proj_0(elt, Trivial) ⊗ proj_0(elt, Trivial) + proj_1(elt, Trivial) ⊗ proj_1(elt, Trivial)
    return D + im * (swap(elt, Trivial) - D)
end

"""
    dcx([eltype::Type{<:Number}], [symmetry::Type{<:Sector}])
    DCX([eltype::Type{<:Number}], [symmetry::Type{<:Sector}])

The double-CNOT gate: two back-to-back CNOTs with alternating control and target.

Supported symmetries: `Trivial`.
"""
@operator DCX function dcx(elt::Type{<:Number}, ::Type{Trivial})
    # the CNOT with control and target interchanged, applied after the regular CNOT
    cx = id(elt, qubit_space()) ⊗ proj_0(elt, Trivial) +
        pauli_x(elt, Trivial) ⊗ proj_1(elt, Trivial)
    return cx * cnot(elt, Trivial)
end

"""
    ecr([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}])
    ECR([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}])

The echoed cross-resonance gate ``\\mathrm{ECR} = \\tfrac{1}{√2}(X ⊗ I - Y ⊗ X)``.

Supported symmetries: `Trivial`.
"""
@operator ECR function ecr(elt::Type{<:Number}, ::Type{Trivial})
    _require_complex(elt, :ecr)
    h = convert(elt, signedroot(1 // 2))
    x, y = pauli_x(elt, Trivial), pauli_y(elt, Trivial)
    return h * (x ⊗ id(elt, qubit_space()) - y ⊗ x)
end

# Two-qubit rotation gates
# ------------------------
"""
    rotation_xx([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}]; theta)
    Rxx([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}]; theta)

The XX-rotation (Ising coupling) gate ``e^{-iθ\\, X ⊗ X / 2} = \\cos\\tfrac{θ}{2}\\,I ⊗ I - i\\sin\\tfrac{θ}{2}\\,X ⊗ X``,
with required rotation angle `theta`.

Supported symmetries: `Trivial`, `Z2Irrep`.
"""
@operator Rxx function rotation_xx(elt::Type{<:Number}, ::Type{Trivial}; theta)
    _require_complex(elt, :rotation_xx)
    return _rotation(pauli_x(elt, Trivial) ⊗ pauli_x(elt, Trivial), theta)
end

"""
    rotation_yy([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}]; theta)
    Ryy([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}]; theta)

The YY-rotation gate ``e^{-iθ\\, Y ⊗ Y / 2} = \\cos\\tfrac{θ}{2}\\,I ⊗ I - i\\sin\\tfrac{θ}{2}\\,Y ⊗ Y``,
with required rotation angle `theta`.

Supported symmetries: `Trivial`, `Z2Irrep`.
"""
@operator Ryy function rotation_yy(elt::Type{<:Number}, ::Type{Trivial}; theta)
    _require_complex(elt, :rotation_yy)
    return _rotation(pauli_y(elt, Trivial) ⊗ pauli_y(elt, Trivial), theta)
end

"""
    rotation_zz([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}]; theta)
    Rzz([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}]; theta)

The ZZ-rotation gate ``e^{-iθ\\, Z ⊗ Z / 2} = \\cos\\tfrac{θ}{2}\\,I ⊗ I - i\\sin\\tfrac{θ}{2}\\,Z ⊗ Z``,
with required rotation angle `theta`.

Supported symmetries: `Trivial`, `Z2Irrep`, `U1Irrep`.
"""
@operator Rzz function rotation_zz(elt::Type{<:Number}, ::Type{Trivial}; theta)
    _require_complex(elt, :rotation_zz)
    return _rotation(pauli_z(elt, Trivial) ⊗ pauli_z(elt, Trivial), theta)
end

"""
    rotation_zx([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}]; theta)
    Rzx([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}]; theta)

The ZX-rotation gate ``e^{-iθ\\, Z ⊗ X / 2} = \\cos\\tfrac{θ}{2}\\,I ⊗ I - i\\sin\\tfrac{θ}{2}\\,Z ⊗ X``,
with required rotation angle `theta`.

Supported symmetries: `Trivial`.
"""
@operator Rzx function rotation_zx(elt::Type{<:Number}, ::Type{Trivial}; theta)
    _require_complex(elt, :rotation_zx)
    return _rotation(pauli_z(elt, Trivial) ⊗ pauli_x(elt, Trivial), theta)
end

# Three-qubit gates
# -----------------
"""
    toffoli([eltype::Type{<:Number}], [symmetry::Type{<:Sector}])
    TOFFOLI([eltype::Type{<:Number}], [symmetry::Type{<:Sector}])
    CCX([eltype::Type{<:Number}], [symmetry::Type{<:Sector}])

The Toffoli (CCX) gate ``|0⟩⟨0| ⊗ I ⊗ I + |1⟩⟨1| ⊗ \\mathrm{CNOT}``: applies [`pauli_x`](@ref) to the third qubit if the first two are both ``|1⟩``.

Supported symmetries: `Trivial`.
"""
@operator TOFFOLI function toffoli(elt::Type{<:Number}, ::Type{Trivial})
    return controlled(cnot(elt, Trivial))
end
const CCX = toffoli

"""
    fredkin([eltype::Type{<:Number}], [symmetry::Type{<:Sector}])
    FREDKIN([eltype::Type{<:Number}], [symmetry::Type{<:Sector}])
    CSWAP([eltype::Type{<:Number}], [symmetry::Type{<:Sector}])

The Fredkin (CSWAP) gate ``|0⟩⟨0| ⊗ I ⊗ I + |1⟩⟨1| ⊗ \\mathrm{SWAP}``: swaps the last two qubits if the first is ``|1⟩``.

Supported symmetries: `Trivial`, `Z2Irrep`, `U1Irrep`.
"""
@operator FREDKIN function fredkin(elt::Type{<:Number}, ::Type{Trivial})
    return controlled(swap(elt, Trivial))
end
const CSWAP = fredkin

end
