module SpinOperators

using TensorKit
using LinearAlgebra: I
using RationalRoots: signedroot
import ..TensorKitTensors: symmetrize, desymmetrize, @operator

export spin_space, basis_transform, casimir
export S_x, S_y, S_z, S_plus, S_min
export S_x_S_x, S_y_S_y, S_z_S_z, S_plus_S_min, S_min_S_plus, S_exchange
export σˣ, σʸ, σᶻ, σ⁺, σ⁻
export Sˣ, Sʸ, Sᶻ, S⁺, S⁻
export SˣSˣ, SʸSʸ, SᶻSᶻ, S⁺S⁻, S⁻S⁺, SS

"""
    spin_space([symmetry::Type{<:Sector}]; spin=1 // 2)

Return the local Hilbert space for a spin-`spin` site with the given symmetry.

| Symmetry | Space |
|---|---|
| `Trivial` | `ComplexSpace(2s+1)` |
| `Z2Irrep` | `Z2Space(0 => 1, 1 => 1)` (spin-1/2 only) |
| `U1Irrep` | `U1Space(m => 1 for m in -s:s)` |
| `SU2Irrep` | `SU2Space(s => 1)` |
"""
spin_space(::Type{Trivial} = Trivial; spin = 1 // 2) = ComplexSpace(Int(2 * spin + 1))
function spin_space(::Type{Z2Irrep}; spin = 1 // 2)
    spin == 1 // 2 || throw(ArgumentError("Z2 symmetry only implemented for spin 1//2"))
    return Z2Space(0 => 1, 1 => 1)
end
spin_space(::Type{U1Irrep}; spin = 1 // 2) = U1Space(i => 1 for i in (-spin):spin)
spin_space(::Type{SU2Irrep}; spin = 1 // 2) = SU2Space(spin => 1)
spin_space(symmetry::Type{<:Sector}; kwargs...) = throw(ArgumentError("invalid symmetry `$symmetry`"))

"""
    basis_transform(symmetry::Type{<:Sector}; spin = 1 // 2)

Return the unitary basis transformation that maps the standard spin basis ``\\{|s⟩, |s-1⟩, …, |-s⟩\\}``
(the eigenbasis of ``S^z`` in descending order of ``m``, as used by the `Trivial` operators)
onto the basis of `spin_space(symmetry; spin)`, as a `TensorMap` on `spin_space(Trivial; spin)` to `desymmetrize(spin_space(symmetry; spin))`.
See also [`symmetrize`](@ref TensorKitTensors.symmetrize).

| Symmetry | Transformation |
|---|---|
| `Trivial` | identity |
| `Z2Irrep` | Hadamard matrix ``\\begin{pmatrix} 1 & 1 \\\\ 1 & -1 \\end{pmatrix}/\\sqrt{2}`` |
| `U1Irrep` | permutation to the order of `sectors(spin_space(U1Irrep; spin))` |
| `SU2Irrep` | identity |

For `Z2Irrep` (spin-1/2 only), the symmetry is the ``ℤ₂`` spin-flip generated by ``2S^x``,
and the Hadamard matrix maps onto its eigenbasis ``|±⟩ = (|↑⟩ ± |↓⟩)/√2``, where
`Z2Irrep(0)` labels the flip-symmetric state ``|+⟩``.

For `U1Irrep`, the ``S^z`` eigenvalue ``m`` is used as the ``U(1)`` charge, and the
transformation is the permutation from descending-``m`` order to TensorKit's charge order
(``0, 1, -1, 2, …`` for integer spin, ``1/2, -1/2, 3/2, …`` for half-integer spin).

For `SU2Irrep`, TensorKit's basis convention within an irrep is descending ``m``, which
coincides with the standard spin basis, such that the transformation is the identity.
"""
function basis_transform(::Type{Trivial}; spin = 1 // 2)
    V = spin_space(Trivial; spin)
    d = Int(2 * spin + 1)
    return TensorMap(Matrix{Int}(I, d, d), V ← V)
end
function basis_transform(::Type{Z2Irrep}; spin = 1 // 2)
    spin == 1 // 2 || throw(ArgumentError("Z2 symmetry only implemented for spin 1//2"))
    h = signedroot(1 // 2)
    V = spin_space(Trivial; spin)
    return TensorMap([h h; h -h], desymmetrize(spin_space(Z2Irrep; spin)) ← V)
end
function basis_transform(::Type{U1Irrep}; spin = 1 // 2)
    V = spin_space(U1Irrep; spin)
    d = Int(2 * spin + 1)
    U = zeros(Int, d, d)
    for (row, c) in enumerate(sectors(V))
        U[row, Int(spin - c.charge + 1)] = 1
    end
    return TensorMap(U, desymmetrize(V) ← spin_space(Trivial; spin))
end
function basis_transform(::Type{SU2Irrep}; spin = 1 // 2)
    V = spin_space(Trivial; spin)
    d = Int(2 * spin + 1)
    return TensorMap(Matrix{Int}(I, d, d), desymmetrize(spin_space(SU2Irrep; spin)) ← V)
end

# Symmetrize a spin operator through its basis transformation
_symmetrize_operator(O::AbstractTensorMap, symmetry::Type{<:Sector}; kwargs...) =
    symmetrize(O, basis_transform(symmetry; kwargs...), spin_space(symmetry; kwargs...))

# Pauli matrices
# --------------
function _pauliterm(spin, i, j)
    1 <= i <= 2 * spin + 1 || return 0.0
    1 <= j <= 2 * spin + 1 || return 0.0
    return sqrt((spin + 1) * (i + j - 1) - i * j) / 2.0
end

"""
    casimir(spin::Real)
    casimir(c::SU2Irrep)

Return the value of the quadratic Casimir ``C_2(s) = s(s+1)`` for SU(2).
"""
casimir(spin::Real) = spin * (spin + 1)
casimir(c::SU2Irrep) = casimir(c.j)

"""
    spinmatrices(spin [, eltype])

The spinmatrices according to [Wikipedia](https://en.wikipedia.org/wiki/Spin_(physics)#Higher_spins).
"""
function spinmatrices(spin, elt = ComplexF64)
    N = Int(2 * spin)

    Sx = zeros(elt, N + 1, N + 1)
    Sy = zeros(complex(elt), N + 1, N + 1)
    Sz = zeros(elt, N + 1, N + 1)

    for row in 1:(N + 1)
        for col in 1:(N + 1)
            term = _pauliterm(spin, row, col)

            if (row + 1 == col)
                Sx[row, col] += term
                Sy[row, col] -= 1im * term
            end

            if (row == col + 1)
                Sx[row, col] += term
                Sy[row, col] += 1im * term
            end

            if (row == col)
                Sz[row, col] += spin + 1 - row
            end
        end
    end
    return Sx, Sy, Sz, one(Sx)
end

# Single-site operators
# ---------------------
"""
    S_x([eltype::Type{<:Number}], [symmetry::Type{<:Sector}]; spin=1 // 2)
    Sˣ([eltype::Type{<:Number}], [symmetry::Type{<:Sector}]; spin=1 // 2)

The spin-x operator ``S^x = \\tfrac{1}{2}(S^+ + S^-)``.

Compatible symmetries: `Trivial`, `Z2Irrep`.

See also [`σˣ`](@ref) (Pauli version ``\\sigma^x = 2S^x``).
"""
@operator Sˣ S_x(::Type{<:Number}, ::Type{<:Sector}; spin)
function S_x(elt::Type{<:Number}, ::Type{Trivial}; spin = 1 // 2)
    S_x_mat, = spinmatrices(spin, elt)
    pspace = spin_space(Trivial; spin)
    return TensorMap(S_x_mat, pspace ← pspace)
end

@doc """
    σˣ([eltype::Type{<:Number}], [symmetry::Type{<:Sector}]; spin=1 // 2)

The Pauli-x operator ``\\sigma^x = 2S^x``.

Compatible symmetries: `Trivial`, `Z2Irrep`.

See also [`S_x`](@ref).
""" σˣ
σˣ(args...; kwargs...) = 2 * S_x(args...; kwargs...)

"""
    S_y([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}]; spin=1 // 2)
    Sʸ([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}]; spin=1 // 2)

The spin-y operator ``S^y = \\tfrac{1}{2i}(S^+ - S^-)``.

Compatible symmetries: `Trivial`.

See also [`σʸ`](@ref) (Pauli version ``\\sigma^y = 2S^y``).
"""
@operator Sʸ S_y(::Type{<:Number}, ::Type{<:Sector}; spin)
function S_y(elt::Type{<:Number}, ::Type{Trivial}; spin = 1 // 2)
    # explicit error to avoid infinite recursion:
    elt <: Real && throw(ArgumentError("S_y requires `elt <: Complex`"))
    _, S_y_mat, _ = spinmatrices(spin, elt)
    pspace = spin_space(Trivial; spin)
    return TensorMap(S_y_mat, pspace ← pspace)
end

@doc """
    σʸ([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}]; spin=1 // 2)

The Pauli-y operator ``\\sigma^y = 2S^y``.

Compatible symmetries: `Trivial`.

See also [`S_y`](@ref).
""" σʸ
σʸ(args...; kwargs...) = 2 * S_y(args...; kwargs...)

"""
    S_z([eltype::Type{<:Number}], [symmetry::Type{<:Sector}]; spin=1 // 2)
    Sᶻ([eltype::Type{<:Number}], [symmetry::Type{<:Sector}]; spin=1 // 2)

The spin-z operator, diagonal in the standard basis with eigenvalues
``m \\in \\{s,\\, s{-}1,\\, \\ldots,\\, -s\\}``.

Compatible symmetries: `Trivial`, `U1Irrep`.

See also [`σᶻ`](@ref) (Pauli version ``\\sigma^z = 2S^z``).
"""
@operator Sᶻ S_z(::Type{<:Number}, ::Type{<:Sector}; spin)
function S_z(elt::Type{<:Number}, ::Type{Trivial}; spin = 1 // 2)
    _, _, S_z_mat = spinmatrices(spin, elt)
    pspace = spin_space(Trivial; spin)
    return TensorMap(S_z_mat, pspace ← pspace)
end

@doc """
    σᶻ([eltype::Type{<:Number}], [symmetry::Type{<:Sector}]; spin=1 // 2)

The Pauli-z operator ``\\sigma^z = 2S^z``.

Compatible symmetries: `Trivial`, `U1Irrep`.

See also [`S_z`](@ref).
""" σᶻ
σᶻ(args...; kwargs...) = 2 * S_z(args...; kwargs...)

"""
    S_plus([eltype::Type{<:Number}], [symmetry::Type{<:Sector}]; spin=1 // 2)
    S⁺([eltype::Type{<:Number}], [symmetry::Type{<:Sector}]; spin=1 // 2)

The spin raising operator ``S^+ = S^x + iS^y``, with matrix elements
``\\langle m{+}1 \\vert S^+ \\vert m \\rangle = \\sqrt{s(s+1) - m(m+1)}``.

Compatible symmetries: `Trivial`.

See also [`σ⁺`](@ref) (Pauli version ``\\sigma^+ = 2S^+``).
"""
@operator S⁺ S_plus(::Type{<:Number}, ::Type{<:Sector}; spin)
function S_plus(elt::Type{<:Number}, ::Type{Trivial}; spin = 1 // 2)
    S⁺ = S_x(elt, Trivial; spin) + 1im * S_y(complex(elt), Trivial; spin)
    if elt <: Real
        S⁺ = real(S⁺)
    end
    return S⁺
end

@doc """
    σ⁺([eltype::Type{<:Number}], [symmetry::Type{<:Sector}]; spin=1 // 2)

The Pauli raising operator ``\\sigma^+ = 2S^+``.

Compatible symmetries: `Trivial`.

See also [`S_plus`](@ref).
""" σ⁺
σ⁺(args...; kwargs...) = 2 * S_plus(args...; kwargs...)

"""
    S_min([eltype::Type{<:Number}], [symmetry::Type{<:Sector}]; spin=1 // 2)
    S⁻([eltype::Type{<:Number}], [symmetry::Type{<:Sector}]; spin=1 // 2)

The spin lowering operator ``S^- = S^x - iS^y``, with matrix elements
``\\langle m{-}1 \\vert S^- \\vert m \\rangle = \\sqrt{s(s+1) - m(m-1)}``.

Compatible symmetries: `Trivial`.

See also [`σ⁻`](@ref) (Pauli version ``\\sigma^- = 2S^-``).
"""
@operator S⁻ S_min(::Type{<:Number}, ::Type{<:Sector}; spin)
function S_min(elt::Type{<:Number}, ::Type{Trivial}; spin = 1 // 2)
    S⁻ = S_x(elt, Trivial; spin) - 1im * S_y(complex(elt), Trivial; spin)
    if elt <: Real
        S⁻ = real(S⁻)
    end
    return S⁻
end

@doc """
    σ⁻([eltype::Type{<:Number}], [symmetry::Type{<:Sector}]; spin=1 // 2)

The Pauli lowering operator ``\\sigma^- = 2S^-``.

Compatible symmetries: `Trivial`.

See also [`S_min`](@ref).
""" σ⁻
σ⁻(args...; kwargs...) = 2 * S_min(args...; kwargs...)

# Two site operators
# ------------------
"""
    S_x_S_x([eltype::Type{<:Number}], [symmetry::Type{<:Sector}]; spin=1 // 2)
    SˣSˣ([eltype::Type{<:Number}], [symmetry::Type{<:Sector}]; spin=1 // 2)

The two-site operator ``S^x \\otimes S^x``.

Compatible symmetries: `Trivial`, `Z2Irrep`.
"""
@operator SˣSˣ S_x_S_x(::Type{<:Number}, ::Type{<:Sector}; spin)
function S_x_S_x(elt::Type{<:Number}, ::Type{Trivial}; spin = 1 // 2)
    return S_x(elt, Trivial; spin) ⊗ S_x(elt, Trivial; spin)
end

"""
    S_y_S_y([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}]; spin=1 // 2)
    SʸSʸ([eltype::Type{<:Complex}], [symmetry::Type{<:Sector}]; spin=1 // 2)

The two-site operator ``S^y \\otimes S^y``.

Compatible symmetries: `Trivial`, `Z2Irrep`.
"""
@operator SʸSʸ S_y_S_y(::Type{<:Number}, ::Type{<:Sector}; spin)
function S_y_S_y(elt::Type{<:Number}, ::Type{Trivial}; spin = 1 // 2)
    YY = S_y(complex(elt), Trivial; spin) ⊗ S_y(complex(elt), Trivial; spin)
    return elt <: Real ? real(YY) : YY
end

"""
    S_z_S_z([eltype::Type{<:Number}], [symmetry::Type{<:Sector}]; spin=1 // 2)
    SᶻSᶻ([eltype::Type{<:Number}], [symmetry::Type{<:Sector}]; spin=1 // 2)

The two-site operator ``S^z \\otimes S^z``.

Compatible symmetries: `Trivial`, `U1Irrep`, `Z2Irrep`.
"""
@operator SᶻSᶻ S_z_S_z(::Type{<:Number}, ::Type{<:Sector}; spin)
function S_z_S_z(elt::Type{<:Number}, ::Type{Trivial}; spin = 1 // 2)
    return S_z(elt, Trivial; spin) ⊗ S_z(elt, Trivial; spin)
end

"""
    S_plus_S_min([eltype::Type{<:Number}], [symmetry::Type{<:Sector}]; spin=1 // 2)
    S⁺S⁻([eltype::Type{<:Number}], [symmetry::Type{<:Sector}]; spin=1 // 2)

The two-site operator ``S^+ \\otimes S^-``.

Compatible symmetries: `Trivial`, `U1Irrep`.
"""
@operator S⁺S⁻ S_plus_S_min(::Type{<:Number}, ::Type{<:Sector}; spin)
function S_plus_S_min(elt::Type{<:Number}, ::Type{Trivial}; spin = 1 // 2)
    return S_plus(elt, Trivial; spin) ⊗ S_min(elt, Trivial; spin)
end

"""
    S_min_S_plus([eltype::Type{<:Number}], [symmetry::Type{<:Sector}]; spin=1 // 2)
    S⁻S⁺([eltype::Type{<:Number}], [symmetry::Type{<:Sector}]; spin=1 // 2)

The two-site operator ``S^- \\otimes S^+``.

Compatible symmetries: `Trivial`, `U1Irrep`.
"""
@operator S⁻S⁺ S_min_S_plus(::Type{<:Number}, ::Type{<:Sector}; spin)
function S_min_S_plus(elt::Type{<:Number}, ::Type{Trivial}; spin = 1 // 2)
    return S_min(elt, Trivial; spin) ⊗ S_plus(elt, Trivial; spin)
end

"""
    S_exchange([eltype::Type{<:Number}], [symmetry::Type{<:Sector}]; spin=1 // 2)
    SS([eltype::Type{<:Number}], [symmetry::Type{<:Sector}]; spin=1 // 2)

The Heisenberg exchange operator
```math
\\mathbf{S}_1 \\cdot \\mathbf{S}_2
= S^x_1 S^x_2 + S^y_1 S^y_2 + S^z_1 S^z_2
= \\tfrac{1}{2}(S^+_1 S^-_2 + S^-_1 S^+_2) + S^z_1 S^z_2.
```

For `SU2Irrep` the operator is diagonal in the total-spin basis with eigenvalue
``\\tfrac{1}{2}[C_2(j_{\\text{tot}}) - 2C_2(s)]``, where ``C_2(j) = j(j+1)``.

Compatible symmetries: `Trivial`, `U1Irrep`, `Z2Irrep`, `SU2Irrep`.
"""
@operator SS S_exchange(::Type{<:Number}, ::Type{<:Sector}; spin)
function S_exchange(elt::Type{<:Number}, ::Type{Trivial}; spin = 1 // 2)
    return (S_plus_S_min(elt, Trivial; spin) + S_min_S_plus(elt, Trivial; spin)) / 2 +
        S_z_S_z(elt, Trivial; spin)
end

end
